services:
  user_db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user_service:
    build: ./backend/user_service
    container_name: user_service
    environment:
      DATABASE_URL: postgresql://user:password@user_db:5432/user_service_db
    depends_on:
      - user_db
    ports:
      - "5000:5000"

  post_db:
    image: postgres:15
    container_name: post_db
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post_service_db
    volumes:
      - post_db_data:/var/lib/postgresql/data

  post_service:
    build: ./backend/post_service
    container_name: post_service
    environment:
      DATABASE_URL: postgresql://post:password@post_db:5432/post_service_db
      USER_SERVICE_URL: http://user_service:5000
    depends_on:
      - post_db
      - user_service
    ports:
      - "5001:5000"

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - post_service

volumes:
  user_db_data:
  post_db_data:
