services:
  interaction_db:
    image: postgres:15
    container_name: interaction_db
    environment:
      POSTGRES_USER: interaction
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interaction_service_db
    ports:
      - "5435:5432"
    volumes:
      - interaction_db_data:/var/lib/postgresql/data

  interaction_service:
    build: .
    container_name: interaction_service
    environment:
      DATABASE_URL: postgresql://interaction:password@interaction_db:5432/interaction_service_db
      USER_SERVICE_URL: http://user_service:5000
      POST_SERVICE_URL: http://post_service:5000
      FLASK_APP: app
    ports:
      - "5002:5000"
    depends_on:
      - interaction_db

volumes:
  interaction_db_data:
